/*
 * Mlflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.11.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Model20MlflowRegisteredModelsAliasPostRequest {
    /// Name of the registered model. This field is required.
    #[serde(rename = "name")]
    pub name: String,
    /// Name of the alias. Maximum size depends on storage backend. If an alias with this name already exists, its preexisting value will be replaced by the specified `version`. All storage backends are guaranteed to support alias name values up to 256 bytes in size. This field is required.
    #[serde(rename = "alias")]
    pub alias: String,
    /// Model version number. This field is required.
    #[serde(rename = "version")]
    pub version: String,
}

impl Model20MlflowRegisteredModelsAliasPostRequest {
    pub fn new(name: String, alias: String, version: String) -> Model20MlflowRegisteredModelsAliasPostRequest {
        Model20MlflowRegisteredModelsAliasPostRequest {
            name,
            alias,
            version,
        }
    }
}

