/*
 * Mlflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.11.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Model20MlflowRegisteredModelsCreatePostRequest {
    /// Register models under this name This field is required.
    #[serde(rename = "name")]
    pub name: String,
    /// Additional metadata for registered model.
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<models::Mlflowregisteredmodeltag>>,
    /// Optional description for registered model.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl Model20MlflowRegisteredModelsCreatePostRequest {
    pub fn new(name: String) -> Model20MlflowRegisteredModelsCreatePostRequest {
        Model20MlflowRegisteredModelsCreatePostRequest {
            name,
            tags: None,
            description: None,
        }
    }
}

