/*
 * Mlflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.11.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Model20MlflowRunsLogModelPostRequest {
    /// ID of the run to log under
    #[serde(rename = "run_id", skip_serializing_if = "Option::is_none")]
    pub run_id: Option<String>,
    /// MLmodel file in json format.
    #[serde(rename = "model_json", skip_serializing_if = "Option::is_none")]
    pub model_json: Option<String>,
}

impl Model20MlflowRunsLogModelPostRequest {
    pub fn new() -> Model20MlflowRunsLogModelPostRequest {
        Model20MlflowRunsLogModelPostRequest {
            run_id: None,
            model_json: None,
        }
    }
}

