/*
 * Mlflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.11.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Model20MlflowRegisteredModelsGetLatestVersionsPostRequest {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "stages", skip_serializing_if = "Option::is_none")]
    pub stages: Option<Vec<String>>,
}

impl Model20MlflowRegisteredModelsGetLatestVersionsPostRequest {
    pub fn new() -> Model20MlflowRegisteredModelsGetLatestVersionsPostRequest {
        Model20MlflowRegisteredModelsGetLatestVersionsPostRequest {
            name: None,
            stages: None,
        }
    }
}

