/*
 * Mlflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.11.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Model20MlflowRunsSearchPostRequest {
    #[serde(rename = "experiment_ids", skip_serializing_if = "Option::is_none")]
    pub experiment_ids: Option<Vec<String>>,
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<String>,
    #[serde(rename = "run_view_type", skip_serializing_if = "Option::is_none")]
    pub run_view_type: Option<models::Mlflowviewtype>,
    #[serde(rename = "max_results", skip_serializing_if = "Option::is_none")]
    pub max_results: Option<i32>,
    #[serde(rename = "order_by", skip_serializing_if = "Option::is_none")]
    pub order_by: Option<Vec<String>>,
    #[serde(rename = "page_token", skip_serializing_if = "Option::is_none")]
    pub page_token: Option<String>,
}

impl Model20MlflowRunsSearchPostRequest {
    pub fn new() -> Model20MlflowRunsSearchPostRequest {
        Model20MlflowRunsSearchPostRequest {
            experiment_ids: None,
            filter: None,
            run_view_type: None,
            max_results: None,
            order_by: None,
            page_token: None,
        }
    }
}

