/*
 * Mlflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.11.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Model20MlflowModelVersionsGetDownloadUriGet200Response {
    /// URI corresponding to where artifacts for this model version are stored.
    #[serde(rename = "artifact_uri", skip_serializing_if = "Option::is_none")]
    pub artifact_uri: Option<String>,
}

impl Model20MlflowModelVersionsGetDownloadUriGet200Response {
    pub fn new() -> Model20MlflowModelVersionsGetDownloadUriGet200Response {
        Model20MlflowModelVersionsGetDownloadUriGet200Response {
            artifact_uri: None,
        }
    }
}

