/*
 * Mlflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.11.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Model20MlflowRunsLogInputsPostRequest {
    #[serde(rename = "run_id", skip_serializing_if = "Option::is_none")]
    pub run_id: Option<String>,
    #[serde(rename = "datasets", skip_serializing_if = "Option::is_none")]
    pub datasets: Option<Vec<models::Mlflowdatasetinput>>,
}

impl Model20MlflowRunsLogInputsPostRequest {
    pub fn new() -> Model20MlflowRunsLogInputsPostRequest {
        Model20MlflowRunsLogInputsPostRequest {
            run_id: None,
            datasets: None,
        }
    }
}

