/*
 * Mlflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.11.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Model20MlflowRegisteredModelsRenamePostRequest {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "new_name", skip_serializing_if = "Option::is_none")]
    pub new_name: Option<String>,
}

impl Model20MlflowRegisteredModelsRenamePostRequest {
    pub fn new() -> Model20MlflowRegisteredModelsRenamePostRequest {
        Model20MlflowRegisteredModelsRenamePostRequest {
            name: None,
            new_name: None,
        }
    }
}

