/*
 * Mlflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.11.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Model20MlflowModelVersionsSearchGet200Response {
    #[serde(rename = "model_versions", skip_serializing_if = "Option::is_none")]
    pub model_versions: Option<Vec<models::Mlflowmodelversion>>,
    #[serde(rename = "next_page_token", skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
}

impl Model20MlflowModelVersionsSearchGet200Response {
    pub fn new() -> Model20MlflowModelVersionsSearchGet200Response {
        Model20MlflowModelVersionsSearchGet200Response {
            model_versions: None,
            next_page_token: None,
        }
    }
}

