/*
 * Mlflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.11.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Model20MlflowRunsSearchPost200Response {
    #[serde(rename = "runs", skip_serializing_if = "Option::is_none")]
    pub runs: Option<Vec<models::Mlflowrun>>,
    #[serde(rename = "next_page_token", skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
}

impl Model20MlflowRunsSearchPost200Response {
    pub fn new() -> Model20MlflowRunsSearchPost200Response {
        Model20MlflowRunsSearchPost200Response {
            runs: None,
            next_page_token: None,
        }
    }
}

