/*
 * Mlflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.11.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Model20MlflowModelVersionsCreatePostRequest {
    /// Register model under this name This field is required.
    #[serde(rename = "name")]
    pub name: String,
    /// URI indicating the location of the model artifacts. This field is required.
    #[serde(rename = "source")]
    pub source: String,
    /// MLflow run ID for correlation, if ``source`` was generated by an experiment run in MLflow tracking server
    #[serde(rename = "run_id", skip_serializing_if = "Option::is_none")]
    pub run_id: Option<String>,
    /// Additional metadata for model version.
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<models::Mlflowmodelversiontag>>,
    /// MLflow run link - this is the exact link of the run that generated this model version, potentially hosted at another instance of MLflow.
    #[serde(rename = "run_link", skip_serializing_if = "Option::is_none")]
    pub run_link: Option<String>,
    /// Optional description for model version.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl Model20MlflowModelVersionsCreatePostRequest {
    pub fn new(name: String, source: String) -> Model20MlflowModelVersionsCreatePostRequest {
        Model20MlflowModelVersionsCreatePostRequest {
            name,
            source,
            run_id: None,
            tags: None,
            run_link: None,
            description: None,
        }
    }
}

