/*
 * Mlflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.11.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Model20MlflowRegisteredModelsGetLatestVersionsPostRequest {
    /// Registered model unique name identifier. This field is required.
    #[serde(rename = "name")]
    pub name: String,
    /// List of stages.
    #[serde(rename = "stages", skip_serializing_if = "Option::is_none")]
    pub stages: Option<Vec<String>>,
}

impl Model20MlflowRegisteredModelsGetLatestVersionsPostRequest {
    pub fn new(name: String) -> Model20MlflowRegisteredModelsGetLatestVersionsPostRequest {
        Model20MlflowRegisteredModelsGetLatestVersionsPostRequest {
            name,
            stages: None,
        }
    }
}

