/*
 * Mlflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.11.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Model20MlflowModelVersionsTransitionStagePostRequest {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(rename = "stage", skip_serializing_if = "Option::is_none")]
    pub stage: Option<String>,
    #[serde(rename = "archive_existing_versions", skip_serializing_if = "Option::is_none")]
    pub archive_existing_versions: Option<bool>,
}

impl Model20MlflowModelVersionsTransitionStagePostRequest {
    pub fn new() -> Model20MlflowModelVersionsTransitionStagePostRequest {
        Model20MlflowModelVersionsTransitionStagePostRequest {
            name: None,
            version: None,
            stage: None,
            archive_existing_versions: None,
        }
    }
}

