/*
 * Mlflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.11.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Model20MlflowRegisteredModelsGetLatestVersionsPost200Response {
    #[serde(rename = "model_versions", skip_serializing_if = "Option::is_none")]
    pub model_versions: Option<Vec<models::Mlflowmodelversion>>,
}

impl Model20MlflowRegisteredModelsGetLatestVersionsPost200Response {
    pub fn new() -> Model20MlflowRegisteredModelsGetLatestVersionsPost200Response {
        Model20MlflowRegisteredModelsGetLatestVersionsPost200Response {
            model_versions: None,
        }
    }
}

