/*
 * Mlflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.11.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Mlflowexperiment {
    #[serde(rename = "experiment_id", skip_serializing_if = "Option::is_none")]
    pub experiment_id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "artifact_location", skip_serializing_if = "Option::is_none")]
    pub artifact_location: Option<String>,
    #[serde(rename = "lifecycle_stage", skip_serializing_if = "Option::is_none")]
    pub lifecycle_stage: Option<String>,
    #[serde(rename = "last_update_time", skip_serializing_if = "Option::is_none")]
    pub last_update_time: Option<i64>,
    #[serde(rename = "creation_time", skip_serializing_if = "Option::is_none")]
    pub creation_time: Option<i64>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<models::Mlflowexperimenttag>>,
}

impl Mlflowexperiment {
    pub fn new() -> Mlflowexperiment {
        Mlflowexperiment {
            experiment_id: None,
            name: None,
            artifact_location: None,
            lifecycle_stage: None,
            last_update_time: None,
            creation_time: None,
            tags: None,
        }
    }
}

