/*
 * Mlflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.11.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Mlflowservicesearchexperiments200Response {
    /// Experiments that match the search criteria
    #[serde(rename = "experiments", skip_serializing_if = "Option::is_none")]
    pub experiments: Option<Vec<models::Mlflowexperiment>>,
    /// Token that can be used to retrieve the next page of experiments. An empty token means that no more experiments are available for retrieval.
    #[serde(rename = "next_page_token", skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
}

impl Mlflowservicesearchexperiments200Response {
    pub fn new() -> Mlflowservicesearchexperiments200Response {
        Mlflowservicesearchexperiments200Response {
            experiments: None,
            next_page_token: None,
        }
    }
}

