/*
 * Mlflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.11.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MlflowservicedeleterunRequest {
    /// ID of the run to delete. This field is required.
    #[serde(rename = "run_id")]
    pub run_id: String,
}

impl MlflowservicedeleterunRequest {
    pub fn new(run_id: String) -> MlflowservicedeleterunRequest {
        MlflowservicedeleterunRequest {
            run_id,
        }
    }
}

