/*
 * Mlflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.11.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Mlflowfileinfo {
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(rename = "is_dir", skip_serializing_if = "Option::is_none")]
    pub is_dir: Option<bool>,
    #[serde(rename = "file_size", skip_serializing_if = "Option::is_none")]
    pub file_size: Option<i64>,
}

impl Mlflowfileinfo {
    pub fn new() -> Mlflowfileinfo {
        Mlflowfileinfo {
            path: None,
            is_dir: None,
            file_size: None,
        }
    }
}

