/*
 * Mlflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.11.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Mlflowserviceupdaterun200Response {
    #[serde(rename = "run_info", skip_serializing_if = "Option::is_none")]
    pub run_info: Option<Box<models::Mlflowruninfo>>,
}

impl Mlflowserviceupdaterun200Response {
    pub fn new() -> Mlflowserviceupdaterun200Response {
        Mlflowserviceupdaterun200Response {
            run_info: None,
        }
    }
}

