/*
 * Mlflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.11.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Mlflowruninputs {
    #[serde(rename = "dataset_inputs", skip_serializing_if = "Option::is_none")]
    pub dataset_inputs: Option<Vec<models::Mlflowdatasetinput>>,
}

impl Mlflowruninputs {
    pub fn new() -> Mlflowruninputs {
        Mlflowruninputs {
            dataset_inputs: None,
        }
    }
}

