/*
 * Mlflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.11.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Mlflowmodelversionstatus {
    #[serde(rename = "PENDING_REGISTRATION")]
    PendingRegistration,
    #[serde(rename = "FAILED_REGISTRATION")]
    FailedRegistration,
    #[serde(rename = "READY")]
    Ready,

}

impl ToString for Mlflowmodelversionstatus {
    fn to_string(&self) -> String {
        match self {
            Self::PendingRegistration => String::from("PENDING_REGISTRATION"),
            Self::FailedRegistration => String::from("FAILED_REGISTRATION"),
            Self::Ready => String::from("READY"),
        }
    }
}

impl Default for Mlflowmodelversionstatus {
    fn default() -> Mlflowmodelversionstatus {
        Self::PendingRegistration
    }
}

