/*
 * Mlflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.11.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MlflowservicesetexperimenttagRequest {
    /// ID of the experiment under which to log the tag. Must be provided. This field is required.
    #[serde(rename = "experiment_id")]
    pub experiment_id: String,
    /// Name of the tag. Maximum size depends on storage backend. All storage backends are guaranteed to support key values up to 250 bytes in size. This field is required.
    #[serde(rename = "key")]
    pub key: String,
    /// String value of the tag being logged. Maximum size depends on storage backend. All storage backends are guaranteed to support key values up to 5000 bytes in size. This field is required.
    #[serde(rename = "value")]
    pub value: String,
}

impl MlflowservicesetexperimenttagRequest {
    pub fn new(experiment_id: String, key: String, value: String) -> MlflowservicesetexperimenttagRequest {
        MlflowservicesetexperimenttagRequest {
            experiment_id,
            key,
            value,
        }
    }
}

