/*
 * Mlflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.11.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Mlflowservicesearchruns200Response {
    /// Runs that match the search criteria.
    #[serde(rename = "runs", skip_serializing_if = "Option::is_none")]
    pub runs: Option<Vec<models::Mlflowrun>>,
    /// 
    #[serde(rename = "next_page_token", skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
}

impl Mlflowservicesearchruns200Response {
    pub fn new() -> Mlflowservicesearchruns200Response {
        Mlflowservicesearchruns200Response {
            runs: None,
            next_page_token: None,
        }
    }
}

