/*
 * Mlflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.11.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MlflowserviceupdateexperimentRequest {
    /// ID of the associated experiment. This field is required.
    #[serde(rename = "experiment_id")]
    pub experiment_id: String,
    /// If provided, the experiment's name is changed to the new name. The new name must be unique.
    #[serde(rename = "new_name", skip_serializing_if = "Option::is_none")]
    pub new_name: Option<String>,
}

impl MlflowserviceupdateexperimentRequest {
    pub fn new(experiment_id: String) -> MlflowserviceupdateexperimentRequest {
        MlflowserviceupdateexperimentRequest {
            experiment_id,
            new_name: None,
        }
    }
}

