/*
 * Mlflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.11.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Mlflowservicegetexperiment200Response {
    #[serde(rename = "experiment", skip_serializing_if = "Option::is_none")]
    pub experiment: Option<Box<models::Mlflowexperiment>>,
}

impl Mlflowservicegetexperiment200Response {
    pub fn new() -> Mlflowservicegetexperiment200Response {
        Mlflowservicegetexperiment200Response {
            experiment: None,
        }
    }
}

