/*
 * Mlflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.11.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Mlflowservicecreaterun200Response {
    #[serde(rename = "run", skip_serializing_if = "Option::is_none")]
    pub run: Option<Box<models::Mlflowrun>>,
}

impl Mlflowservicecreaterun200Response {
    pub fn new() -> Mlflowservicecreaterun200Response {
        Mlflowservicecreaterun200Response {
            run: None,
        }
    }
}

