/*
 * Mlflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.11.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelregistryservicerenameregisteredmodelRequest {
    /// Registered model unique name identifier. This field is required.
    #[serde(rename = "name")]
    pub name: String,
    /// If provided, updates the name for this ``registered_model``.
    #[serde(rename = "new_name", skip_serializing_if = "Option::is_none")]
    pub new_name: Option<String>,
}

impl ModelregistryservicerenameregisteredmodelRequest {
    pub fn new(name: String) -> ModelregistryservicerenameregisteredmodelRequest {
        ModelregistryservicerenameregisteredmodelRequest {
            name,
            new_name: None,
        }
    }
}

