/*
 * Mlflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.11.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Modelregistryservicecreateregisteredmodel200Response {
    #[serde(rename = "registered_model", skip_serializing_if = "Option::is_none")]
    pub registered_model: Option<Box<models::Mlflowregisteredmodel>>,
}

impl Modelregistryservicecreateregisteredmodel200Response {
    pub fn new() -> Modelregistryservicecreateregisteredmodel200Response {
        Modelregistryservicecreateregisteredmodel200Response {
            registered_model: None,
        }
    }
}

