/*
 * Mlflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.11.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Modelregistryservicegetlatestversions200Response {
    /// Latest version models for each requests stage. Only return models with current ``READY`` status. If no ``stages`` provided, returns the latest version for each stage, including ``\"None\"``.
    #[serde(rename = "model_versions", skip_serializing_if = "Option::is_none")]
    pub model_versions: Option<Vec<models::Mlflowmodelversion>>,
}

impl Modelregistryservicegetlatestversions200Response {
    pub fn new() -> Modelregistryservicegetlatestversions200Response {
        Modelregistryservicegetlatestversions200Response {
            model_versions: None,
        }
    }
}

